project:
  type: website
  output-dir: docs

website:
  title: "Nicolas Chopin"
  site-url: https://nchopin.github.io/
  description: "NC's website"
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "Papers"
        href: papers.html
      - text: "Book"
        href: books.html
      - text: "Software"
        href: software.html
      - text: "Teaching"
        href: teaching.html
      - text: "CV"
        href: files/cv.pdf
      - text: "Blog"
        href: https://statisfaction-blog.github.io/

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css



