project:
  type: website
  output-dir: docs

website:
  title: "Nicolas Chopin"
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "Papers"
        href: papers.html
      - text: "Book"
        href: books.html
      - text: "Software"
        href: software.html
      - text: "Teaching"
        href: teaching.html
      - text: "CV"
        href: files/cv.pdf
      - text: "Blog"
        href: blog.html
      - icon: rss
        href: blog.xml

format:
  html:
    theme: flatly
    css: styles.css



